Updated README.md, closes #985 #992
OpenMage/magento-lts pull request #1160
Opened 2020-08-22 03:50 UTC by sreichel

### Description (*)

- add branch alias to composer.json (see https://github.com/OpenMage/magento-lts/pull/992#issuecomment-638974892)
- add AFL 3.0 license
- removed duplicate LICENSE.html
- removed some git related text
- added some more info about 
  - new config options
  - new events
- updated install instructions (see #992) 

### Related Pull Requests

- OpenMage/magento-lts#992

### Fixed Issues (if relevant)

- Fixes OpenMage/magento-lts#985

### Questions or comments

- its WIP
- help wanted
- ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

2020-09-01 11:19 UTC, kkrieger85 submitted a review, later dismissed
Yeah. Thx

2020-09-01 11:57 UTC, tmotyl commented on README.md
> +composer require openmage/magento-lts":"dev-master"
is dev-master correct here? we don't have master branch

2020-09-01 11:58 UTC, tmotyl submitted a review, later dismissed

2020-09-01 15:19 UTC, Flyingmana requested changes
Please use something else than "dev-master"

Master is a deprecated term/phrase. Following githubs naming here, "dev-main" would be an appropriate alternative.

2020-09-15 17:06 UTC, colinmollenhour commented
Looks good! No objections.

On the section for "If you want to contribute to the project:" what about mentioning the one-step dev environment by either adding a link to the [README](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/dev/openmage/README.md) or adding the command to the list of shell commands given?

```
# Step 1: clone your fork
git clone https://github.com/<YOUR GIT USERNAME>/magento-lts
cd magento-lts
git remote add upstream https://github.com/OpenMage/magento-lts
git pull upstream 1.9.4.x

# Step 2: start the dev environment
dev/openmage/install.sh

# Step 3: hack some improvements and create a Pull Request
git checkout -b your-branch
git add -A
git commit
git push origin your-branch
```

2021-01-22 00:47 UTC, sreichel commented on README.md
> +- `catalog/product_image/progressive_threshold`
```suggestion
- `admin/emails/admin_notification_email_template`
- `adminhtml_sales_order_create_save_before`
- `catalog/product_image/progressive_threshold`
```

Added new event #1168

2021-01-22 00:53 UTC, sreichel commented on README.md
> +- `sitemap_cms_pages_generating_before`
```suggestion
- 'adminhtml_sales_order_create_save_before'
- `checkout_cart_product_add_before`
- `sitemap_cms_pages_generating_before`
```
Added event #1168
Added #1168

2021-01-22 01:04 UTC, sreichel commented
> what about mentioning the one-step dev environment

@colinmollenhour  Absolutely, but I'd like to leave that up to you. I would prefer the link to a README, this one you can manage yourself without needing PRs here.

2021-01-22 23:37 UTC, colinmollenhour approved these changes

2021-01-23 16:07 UTC, kkrieger85 approved these changes

2021-02-13 11:21 UTC, Flyingmana approved these changes

2021-02-13 11:21 UTC, merged