Fix notice when there are no sales rules for a given situation
OpenMage/magento-lts pull request #1326
Opened 2020-12-03 15:48 UTC by aredridel

### Description (*)

When there are no sales rules for a given combination of website, customer group and coupon code, a notice is generated. This checks more carefully to not emit the notice and just return null.

### Manual testing scenarios (*)

I'm not sure how to trigger the code path without third party extension code.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-04 00:47 UTC, kiatng approved these changes

2020-12-07 18:23 UTC, colinmollenhour submitted a review, later dismissed

2021-01-10 01:36 UTC, sreichel requested changes

2021-01-10 01:36 UTC, sreichel commented on app/code/core/Mage/SalesRule/Model/Validator.php
> +        return isset($this->_rules[$key]) ? $this->_rules[$key] :  null;
```suggestion
        return $this->_rules[$key] ?? null;
```

2021-01-10 01:37 UTC, sreichel approved these changes

2021-03-31 21:28 UTC, aredridel commented
Is there more that needs to be done to get this merged?

2021-04-01 00:15 UTC, kiatng approved these changes

2021-04-01 03:35 UTC, colinmollenhour approved these changes

2021-04-29 08:50 UTC, merged