Allow min pass length to 5 during login
OpenMage/magento-lts pull request #1330
Opened 2020-12-08 09:05 UTC by maximehuran

### Description (*)

Allow customer to login with a password of 5 characters. It will avoid to have some customers who cannot login because their current password is less than 7 characters.

### Related Pull Requests

No related pull request found.

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#855  

### Manual testing scenarios (*)

1. Try to login with a password with less than 7 characters but more than 5.
2. You will not have the JS validation which tells you that your password is too short.

### Questions or comments

We can decrease the limit of 5 characters if necessary. I don't know the old minimum password length.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-08 11:46 UTC, jouriy commented
I would suggest to not hardcode this into templates, but use `getMinPasswordLength()` like this:
```diff
 +                    <?php $minPasswordLength = max((int)$this->getCustomer()->getMinPasswordLength(), Mage_Core_Model_App::ABSOLUTE_MIN_PASSWORD_LENGTH); ?>
+                    <input type="password"
+                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>"
+                           class="input-text required-entry validate-password min-pass-length-<?php echo $minPasswordLength ?>"
+                           name="password"
+                           id="password" />

2020-12-08 11:49 UTC, jouriy requested changes
Sorry, I misunderstood the purpose of these changes. Please ignore my review.

2020-12-08 12:00 UTC, jouriy approved these changes

2020-12-08 13:51 UTC, maximehuran commented
ping @colinmollenhour

2020-12-08 15:22 UTC, colinmollenhour approved these changes
Looks good, thanks!

2020-12-09 01:37 UTC, kiatng approved these changes

2020-12-09 07:50 UTC, m-overlund approved these changes

2020-12-15 09:36 UTC, maximehuran commented
Any update ? :)

2020-12-29 02:43 UTC, sreichel approved these changes

2021-01-10 03:57 UTC, merged