Updating phpstorm meta files with magerun 2.1.0
OpenMage/magento-lts pull request #1365
Opened 2020-12-28 23:14 UTC by boesbo

Updating phpstorm meta files with magerun 2.1.0. This solves the compatibility problem with the PHPStorm Stubs library used for example in the vscode PHP-Intelephense extension.

### Related Pull Requests
https://github.com/netz98/n98-magerun/pull/1141

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2020-12-29 16:16 UTC, colinmollenhour reviewed
It looks like this adds some classes that don't exist in the core.

2021-01-07 10:48 UTC, Flyingmana submitted a review, later dismissed

2021-01-08 01:57 UTC, kiatng approved these changes

2021-01-14 23:10 UTC, sreichel commented on .phpstorm.meta.php/magento_blocks_methods.meta.php
> +            'adminhtml/notification_symlink' => \Mage_Adminhtml_Block_Notification_Symlink::class,
No such file.

2021-01-14 23:10 UTC, sreichel commented on .phpstorm.meta.php/magento_blocks_methods.meta.php
> +            'adminhtml/sales_order_view_tab_prova' => \Mage_Adminhtml_Block_Sales_Order_View_Tab_Prova::class,
No such file.

2021-01-14 23:18 UTC, sreichel requested changes
Please remove that two classes.

2021-01-14 23:19 UTC, sreichel approved these changes

2021-03-02 10:28 UTC, kiatng approved these changes

2021-03-03 15:53 UTC, colinmollenhour approved these changes

2021-03-11 00:54 UTC, merged