Simplified true/false
OpenMage/magento-lts pull request #1398
Opened 2021-01-14 22:12 UTC by sreichel

### Description (*)

Removed unnecessary true/false

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-11 04:22 UTC, kiatng commented on app/code/core/Mage/Adminhtml/Block/Catalog/Category/Tree.php
> +        $item['allowDrag'] = $allowMove && (!($node->getLevel() == 1 && $rootForStores));
Unnecessary brackets?

```suggestion
$item['allowDrag'] = $allowMove && !($node->getLevel() == 1 && $rootForStores);
```

2021-03-11 04:28 UTC, kiatng commented on app/code/core/Mage/Core/Model/Config.php
> +                'active'    => ('true' === (string)$moduleNode->active),
Me think is this:

```suggestion
                'active'    => (bool)(string)$moduleNode->active,
```

2021-03-11 04:36 UTC, kiatng commented on app/code/core/Mage/Admin/Model/User.php
> +        return (is_array($result) && count($result) > 0);
Is it better without brackets?

```suggestion
        return is_array($result) && count($result) > 0;
```

2021-03-11 04:57 UTC, kiatng requested changes

2021-03-11 04:57 UTC, kiatng commented on app/code/core/Mage/Core/Model/Config.php
> +                'active'    => ('true' === (string)$moduleNode->active),
My preference:

```suggestion
                'active'    => (string)$moduleNode->active === 'true',
```

2021-03-11 04:57 UTC, kiatng commented on app/code/core/Mage/Admin/Model/User.php
> +        return (is_array($result) && count($result) > 0);
```suggestion
        return is_array($result) && count($result) > 0;
```

2021-03-11 04:57 UTC, kiatng commented on app/code/core/Mage/Api/Model/User.php
> +        return (is_array($result) && count($result) > 0);
```suggestion
        return is_array($result) && count($result) > 0;
```

2021-03-11 04:57 UTC, kiatng commented on app/code/core/Mage/Api/Model/User.php
> +        return (is_array($result) && count($result) > 0);
```suggestion
        return is_array($result) && count($result) > 0;
```

2021-03-12 08:57 UTC, kiatng approved these changes
Thank you.

2021-03-12 09:05 UTC, kkrieger85 approved these changes

2021-03-12 16:37 UTC, colinmollenhour approved these changes

2021-03-12 18:14 UTC, merged