Update Interface.php
OpenMage/magento-lts pull request #1431
Opened 2021-01-27 10:55 UTC by matteorossi-thespacesm

Part of change to fix bug #1428 on OpenMage LTS 19.4.10

### Description (*)

Add method getProduct to interface

### Related Pull Requests

Add method getProduct to Mage_Catalog_Model_Product_Configuration_Item_Option class

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#1428 on OpenMage LTS 19.4.10<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-02-03 23:06 UTC, kkrieger85 approved these changes

2021-07-15 10:01 UTC, fballiano commented
modify the interface could create breaking changes?

2021-07-16 01:15 UTC, kiatng commented
> modify the interface could create breaking changes?

Yes, it would. Not only that, it will break existing classes which implement the interface, and we happen to have one such class:
https://github.com/OpenMage/magento-lts/blob/f71321b37a782bd167ef56de0c6e18e67645685d/app/code/core/Mage/Catalog/Model/Product/Configuration/Item/Option.php#L34-L44

This PR should not be merged.

2021-07-16 06:25 UTC, Flyingmana requested changes
Blocked for reasons of BC incompatibility mentioned in the comments.

Alternatives:
- Add a new Interface for this method, which is used by the classes where this method is relevant
- not adding it (where is this method currently used from the outside, where we need it?)
- adding the interface only in later versions

2021-07-16 07:39 UTC, fballiano commented
@Flyingmana @kiatng the class was already fixed in https://github.com/OpenMage/magento-lts/pull/1432 but the problem kinda still exists if somebody extended the interface, would somebody do that to that component? I mean, if the getproduct method is necessary than we could add in https://github.com/OpenMage/magento-lts/pull/1432 without modifying the interface and case closed, right?

2021-07-16 09:40 UTC, kiatng commented
I agree with @fballiano. So, definitely not in branch 19. May be branch 20?

2022-05-27 12:11 UTC, luigifab commented
I vote for close them.

2022-07-10 11:37 UTC, closed without merging