Mage_Core_Model_Abstract: Fix rollback when Throwable is thrown in save method
OpenMage/magento-lts pull request #1483
Opened 2021-03-03 23:06 UTC by Sekiphp

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes OpenMage/magento-lts#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-04 10:25 UTC, midlan approved these changes

2021-03-04 10:27 UTC, LukasCesal approved these changes

2021-03-04 10:28 UTC, LukasCesal commented
Funny when you are upgrading to LTS and get another bunch of errors :-) thank you Luboš

2021-03-04 20:03 UTC, J-Kostecka commented
This might also solve PZ-4381 - products disappearing randomly after import

2021-03-09 10:58 UTC, kiatng commented
See also PR #1442

2021-03-10 04:50 UTC, kiatng commented
@Sekiphp First, as you said, you have already fixed this in your project. Others facing similar issue can likewise fix them in their respective projects, no issue there. Second, for maintaining OpenMage code base, we need to fix `Throwable` for all instances, this helps to maintain code quality in terms of consistency, eg, use of `$t` or `$e`.  We can better progress OpenMage this way. I hope you agree.

2021-03-16 17:18 UTC, colinmollenhour requested changes
Good change! Thanks for the PR!

nitpick: Please fix the vardoc and `delete()` as well while you're at it.

2021-03-18 09:08 UTC, LukasCesal submitted a review, later dismissed

2021-04-06 15:37 UTC, Sekiphp commented
@colinmollenhour Added throws annotation and fixed `delete()` method

+ I changed `Throwable $t` to `Throwable $e`, because I read the specifications, and in official PHP examples is `$e` instead of `$t`:
- https://wiki.php.net/rfc/throwable-interface
- https://github.com/php/php-src/pull/1284

2021-04-06 16:36 UTC, midlan approved these changes

2021-04-07 06:03 UTC, colinmollenhour approved these changes

2021-04-29 10:18 UTC, merged