New event "init_form_values_after" after data set on a form
OpenMage/magento-lts pull request #1485
Opened 2021-03-04 09:04 UTC by woutersamaey

Magento does not have a common event after data is set on a form.
This new event allows us to change the form, the elements and the values once data is entered, giving full flexibility.
I needed this event in a special case where I needed to change the options of a select, to include the current value that was not in the existing options list.
There was no other way to do this without overriding many forms 1 by 1.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-03-04 21:25 UTC, colinmollenhour submitted a review, later dismissed
Excellent addition!

If I was designing from scratch I'd probably add a second event with a default overridable prefix to it like `$this->_eventPrefix.'_form_before_html'` so that the eventPrefix can be added to classes making it easier to override the specific form using the event name (same as models). But with or without this should have been added years ago. :)

2021-03-04 21:55 UTC, sreichel commented
> 
> 
> Excellent addition!
> 
> If I was designing from scratch I'd probably add a second event with a default overridable prefix to it like `$this->_eventPrefix.'_form_before_html'` so that the eventPrefix can be added to classes making it easier to override the specific form using the event name (same as models). But with or without this should have been added years ago. :)

OT: Is it worth tackling #423 again? You had some conserns here https://github.com/OpenMage/magento-lts/pull/423#issuecomment-356660393 ...  but i'm still not sure how to fix it.

2021-03-05 01:13 UTC, kiatng requested changes

2021-03-05 01:13 UTC, kiatng commented on app/code/core/Mage/Adminhtml/Block/Widget/Form.php
> +        Mage::dispatchEvent('init_form_values_after', ['form' => $this]);
I'd like to change 2 things:
1. Event name should follow naming convention
2. The param `form` should be `$this->getForm()`, and `$this` is assigned to param `block`.

```suggestion
Mage::dispatchEvent(
    'adminhtml_block_widget_form_init_form_values_after',
    [
        'block' => $this,
        'form' => $this->getForm()
    ]
);
```

2021-03-05 05:49 UTC, woutersamaey commented
Thanks for the great suggestions @kiatng

2021-03-05 08:19 UTC, kiatng approved these changes

2021-03-08 12:48 UTC, woutersamaey commented
@colinmollenhour and @sreichel can we get this merged?

2021-03-09 01:05 UTC, colinmollenhour approved these changes

2021-03-11 01:59 UTC, sreichel approved these changes

2021-03-11 02:00 UTC, merged