Throwing Exception when column not exists instead of E_NOTICE
OpenMage/magento-lts pull request #1531
Opened 2021-04-07 11:21 UTC by Sekiphp

### Description (*) / Manual testing scenarios (*)
Consider following code:

```php
Mage::getModel('catalog/product')->load('value', 'unexisting_column');
```

Now is show following error:
![image](https://user-images.githubusercontent.com/9967016/113858340-e6a57a80-97a3-11eb-88ac-f77031d4842d.png)

After change is thrown `Exception` with info, which column does not exist.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-04-07 13:48 UTC, kiatng requested changes

2021-04-07 13:48 UTC, kiatng commented on app/code/core/Mage/Core/Model/Resource/Db/Abstract.php
> +            throw new Exception("Column \"{$field}\" does not exists in table \"{$this->getMainTable()}\"");
Fix grammar:
```suggestion
            throw new Exception("Column \"{$field}\" does not exist in table \"{$this->getMainTable()}\"");
```

2021-04-07 16:54 UTC, Sekiphp commented on app/code/core/Mage/Core/Model/Resource/Db/Abstract.php
> +            throw new Exception("Column \"{$field}\" does not exists in table \"{$this->getMainTable()}\"");
Thank you :-)

2021-04-07 21:08 UTC, fballiano approved these changes

2021-04-07 21:08 UTC, fballiano approved these changes

2021-04-07 21:44 UTC, colinmollenhour approved these changes

2021-04-08 00:47 UTC, kiatng approved these changes

2021-04-13 07:12 UTC, midlan approved these changes

2021-04-14 10:55 UTC, merged