Update getNextAutoincrement to not use showTableStatus
OpenMage/magento-lts pull request #1721
Opened 2021-07-06 17:30 UTC by jonashrem

### Description (*)
update getNextAutoincrement to not use showTableStatus for performants reasons.

### Related Pull Requests
https://github.com/magento/magento2/pull/33433
#1712

### Fixed Issues (if relevant)
/

### Manual testing scenarios (*)
test import/export

### Questions or comments
/

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

2022-06-09 02:52 UTC, colinmollenhour commented
Looks great, what is the oldest version of MySQL where this code will work?

2022-06-09 02:55 UTC, colinmollenhour approved these changes

2022-09-29 09:54 UTC, fballiano commented on app/code/core/Mage/ImportExport/Model/Resource/Helper/Mysql4.php
> +            throw new \Magento\Framework\Exception\LocalizedException(__('Cannot get autoincrement value'));
```suggestion
            Mage::throwException(Mage::helper('importexport')->__('Cannot get autoincrement value'));
```

2022-09-29 09:54 UTC, fballiano commented on app/code/core/Mage/ImportExport/Model/Resource/Helper/Mysql4.php
> +
```suggestion
```

2022-09-29 09:55 UTC, fballiano commented on app/code/core/Mage/ImportExport/Model/Resource/Helper/Mysql4.php
> +        {
```suggestion
        if (empty($entityStatus['AUTO_INCREMENT'])) {
```

2022-09-29 09:56 UTC, fballiano commented
was this code tested on OM?

2022-09-29 18:21 UTC, colinmollenhour commented
I confirmed that the "SELECT AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES" query works on MySQL 5.6 and up and MariaDb 10.3 and up. (probably some earlier versions, these are just the oldest I checked)

I've not tested an import in Magento, @jonashrem did you test an import with the latest version of this PR?

2022-09-29 18:23 UTC, colinmollenhour requested changes

2022-09-29 18:23 UTC, colinmollenhour commented on app/code/core/Mage/ImportExport/Model/Resource/Helper/Mysql4.php
> +            $this->quote($tableName)
Should this be like so?
```suggestion
            $connection->quote($tableName)
```

2023-05-15 20:18 UTC, fballiano commented
I've rebased this and tested it briefly creating new customer/addresses/products, the autoincrements work fine.

I've no idea if this is really a performance improvement or if it could create a problem.

But now it's ready to be merged, or it should be closed.

2023-05-15 22:42 UTC, jonashrem commented
Thanks

2023-05-16 02:25 UTC, colinmollenhour approved these changes
Approve, but I didn't perform a end-to-end test.

@jonashrem Please confirm this has been tested in it's current state. Thanks!

2023-09-12 18:32 UTC, empiricompany approved these changes

2023-09-12 18:35 UTC, jonashrem commented
> 

sorry this got under.

I did not test the current variant with up to date OpenMage.

Do you have some specific test szenario in mind?

2023-09-12 18:36 UTC, fballiano commented
I also will test this out as soon as possible

2023-09-13 13:40 UTC, kiatng approved these changes
Tested. It is faster by about 50% to sub mini-sec from 1.5ms.

```php
Mage::getResourceHelper('importexport')->getNextAutoincrement('sales_flat_order_item');
```

2023-09-13 14:04 UTC, fballiano commented
is it possible that the result of this call gets cached somewhere?

on my DB I've an autoincrement value of 65:
<img width="978" alt="Screenshot 2023-09-13 alle 15 03 34" src="https://github.com/OpenMage/magento-lts/assets/909743/63147566-6208-4e93-9797-e0242c72165c">

but when I run this:
<img width="937" alt="Screenshot 2023-09-13 alle 15 03 57" src="https://github.com/OpenMage/magento-lts/assets/909743/4e437217-67dd-4b3c-b0d7-cec4296faa85">

I get 63:
<img width="442" alt="Screenshot 2023-09-13 alle 15 03 54" src="https://github.com/OpenMage/magento-lts/assets/909743/53ccf297-4b14-4aa3-b69a-30f66dfedb08">

2023-09-14 14:44 UTC, colinmollenhour commented
> is it possible that the result of this call gets cached somewhere?

Very odd, I don't see how that is possible.. Are you 100% certain the two tests were run against the same database?

2023-09-14 16:02 UTC, elidrissidev commented
> is it possible that the result of this call gets cached somewhere?

I encountered this issue the first time I tested this PR but forgot to post it. It seems `performance_schema` is not guaranteed to contain the most up-to-date value, sometimes `ANALYZE TABLE` is necessary to get accurate results. Maybe just a simple `MAX() + 1` query would do the job here.

2023-09-14 16:08 UTC, fballiano commented
@colinmollenhour I'm sure it is the same database

@elidrissidev AFAIK `MAX+1` is not safe in some cases, I don't remember exactly on top of my head, zf1 autoincrement function uses the "last insert id", would that be better at that point? or just leave everything is it is now?

2023-09-14 16:45 UTC, colinmollenhour commented
Ahh, I still don't see how essentially the same query via the console and via PHP can have different results, but it appears the information schema data is indeed cached within MySQL for an entire 24 hours by default. This can be controlled by [information_schema_stats_expiry](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_information_schema_stats_expiry). This can be set as a session variable just before the query and yield correct results which isn't a terrible approach, but not sure if that is really an improvement in performance at that point.

Perhaps your ID is setting this session variable behind the scenes and that is why the results are different?

https://stackoverflow.com/a/65996809/187780

The `MAX(id)` seems to be just as fast. It might not be accurate if there were deletions or if there were simultaneous transactions that incremented the auto increment but have not been committed yet or were rolled back (I'm not 100% sure on this but somewhat certain). However, that may not be an issue or even a regression - is this method going to be used in a multi-threaded environment?

2023-09-14 16:48 UTC, fballiano commented
the problem I see is when I run from the PHP CLI, not from the Mysql client (I use SequelAce) which anyway has an expire of 0

<img width="545" alt="Screenshot 2023-09-14 alle 17 47 19" src="https://github.com/OpenMage/magento-lts/assets/909743/addbf9ab-7b9e-4508-9725-bd631c5a8fe2">

2023-09-14 16:54 UTC, fballiano commented
but actually if I run php cli I get an expire of 24h
<img width="400" alt="Screenshot 2023-09-14 alle 17 53 26" src="https://github.com/OpenMage/magento-lts/assets/909743/48cf03c4-0785-4cb7-ae83-42bffb36b522">

weird... I'll try to find where is this set...

2023-09-14 16:57 UTC, colinmollenhour commented
It's probably just a feature of SequelAce so it makes sense now. :)

2023-09-14 17:02 UTC, fballiano commented
If I do something like this:

<img width="920" alt="Screenshot 2023-09-14 alle 18 01 34" src="https://github.com/OpenMage/magento-lts/assets/909743/8858d143-8410-4a57-aa75-66babf5ce91f">

then it works ok.

not sure about all of this :-\

2023-09-14 17:21 UTC, colinmollenhour commented
In my tests `information_schema` method takes about half the time of `show table status`,  but considering you have to set a session variable first it requires two round trips at least on the first use. And then there is possibly a performance penalty of disabling the information schema cache which I have no idea how to measure. The `MAX(id)+1` method is the fastest by far. This is on a very big and active table from a production database. 
![image](https://github.com/OpenMage/magento-lts/assets/38738/2aee8dfa-9231-446e-879f-3fc7d7c71064)

So I think the `MAX()+1` method is a very good suggestion as long as this method isn't used with tables that have deleted rows. If that is not a safe assumption to make (probably isn't) then I think the old method should be kept and no change made since there is not that much benefit for increased complexity and uncertainty.

Perhaps the better change would be to update where this method is used to only call the method once or use `MAX(id)+1` instead but leave getNextAutoincrement alone?

2023-09-14 17:33 UTC, colinmollenhour commented
I don't think stats cache expiry should be set globally if it is not absolutely necessary - that should be up to the DBA to decide ideally. It could be set just before querying information schema, perhaps using a static variable so that it is only done once.

2023-09-14 17:49 UTC, fballiano commented
sure, that's why I was testing it in the initStatement of the openmage connection, if we remove the GLOBAL it still works

<img width="1057" alt="Screenshot 2023-09-14 alle 18 49 22" src="https://github.com/OpenMage/magento-lts/assets/909743/4bbae128-0d5f-4f8d-a3db-4055e23493dc">

<img width="396" alt="Screenshot 2023-09-14 alle 18 49 44" src="https://github.com/OpenMage/magento-lts/assets/909743/2f757204-d77f-49f1-864d-f33ef96fdac9">

2023-09-19 09:39 UTC, fballiano requested changes
I have to block the merge because of https://github.com/OpenMage/magento-lts/pull/1721#issuecomment-1719734451

what are we doing about this?

2023-09-19 09:42 UTC, kiatng commented
I think we should close it.

2023-09-19 09:42 UTC, fballiano commented
me too, unless something completely different comes out, this is too risky

2023-09-19 09:42 UTC, closed without merging