Removed _isMemoryLimitReached() nonsense
OpenMage/magento-lts pull request #1749
Opened 2021-07-30 06:40 UTC by woutersamaey

### Description (*)
If we don't have enough memory, we'll know soon enough. No need to do these computations every time.
### Related Pull Requests

### Questions or comments
- Less time/resources wasted on calculating memory needed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2021-07-30 10:16 UTC, luigifab reviewed
There is also a `_checkMemory` in `Mage_Catalog_Model_Product_Image`. On our store we have added `return true;`.

2021-07-30 10:40 UTC, woutersamaey commented
Good catch @luigifab, I removed these as well.

2021-07-30 12:21 UTC, Flyingmana requested changes

2021-07-30 12:21 UTC, Flyingmana commented on app/code/core/Mage/Catalog/Model/Product/Image.php
> -    protected function _checkMemory($file = null)
also removing the function may break modules using it. Please only remove the usages, and optionally mark the method as deprecated.
Please also do not remove the functionality, yet.

2021-07-30 12:25 UTC, Flyingmana commented
Generally support the removal of the check. The PHP way of reporting reaching the memory limit is actually better and more verbose.
Although, this check allows for a more gracefully fail, as an exception allows handling it, while the php way lets the script die if I remember correctly.

2021-07-30 12:31 UTC, woutersamaey commented
@Flyingmana you are correct, but Magento does nothing with the exception that is worth our consideration.
Any script can run out of memory, so it's up to the developer to watch for memory issues in the PHP log.

2021-07-30 12:38 UTC, Flyingmana commented
@woutersamaey yes, thats why I support the change :)
But we need to keep the protected functions, in case other modules/shops use them on purpose.

2021-07-30 12:41 UTC, woutersamaey commented
@Flyingmana who in their right mind is going to use this on purpose?
I say we clean up a bit and move forward, not stay in place. This is the v20 branch, right?

2021-07-30 12:50 UTC, Flyingmana commented
It is not ours to judge others decision, and I want to please ask you to not talk ill of others, especially  not knowing which circumstances might have lead to these decisions.

Allowing BC breaks in the v20 branch is not an excuse to act reckless in this regard.

2021-07-30 12:52 UTC, woutersamaey commented
Okay, fair enough. I didn't want to be rude, just can't see what possible purpose it could serve.
Is OpenMage ever planning on breaking away or will things stay forever as they are? Would be nice to see a roadmap or something like that...

2021-07-31 14:34 UTC, fballiano commented
I support the cleaning tasks for v20 (some would say too much ehehehe), in this case, seeing you already discussed it, I'd just remove the calls to the "checkmemory" methods and mark all related methods as deprecated, so we can move this PR forward as we're all wasting computing cycles now :-)

2021-08-08 11:38 UTC, elidrissidev commented
I support this. Let's just remove the usages and mark the method as deprecated for the v19 branch.

2022-08-20 07:25 UTC, tobihille approved these changes

2022-08-22 11:37 UTC, tmewes submitted a review, later dismissed

2022-08-22 11:38 UTC, tmewes commented
@fballiano Can you please push the magic button (update the branch with the current version of 20.0) that we get rid of the conflicts and get this PR done? :)

2022-08-22 11:54 UTC, fballiano commented
I've restored the original methods marking them as deprecated, so it should be ready to merge.

But, I can't switch this PR to 1.9.4.x cause it's breaking for some reasons (it generates 90+ commits and 5000 modified files), if you're ok with it I'd close this one and recreate it as a new PR on v19.

2022-08-22 12:12 UTC, tmewes commented
Sounds like a good plan. 👍

2022-08-22 12:16 UTC, fballiano commented
Closing this in favour of https://github.com/OpenMage/magento-lts/pull/2471 which is based on v19 and non-BC :-)

2022-08-22 12:16 UTC, closed without merging