Improve getScheme on Zend_Controller_Request_Http
OpenMage/magento-lts pull request #1872
Opened 2021-10-31 10:34 UTC by mmenozzi

### Description (*)
Some web servers (for example the [local web server of the Symfony CLI](https://symfony.com/doc/current/setup/symfony_server.html#getting-started)) puts the value `On` (and not `on`)  in the `$_SERVER['HTTPS']` super global.

With this PR the `Zend_Controller_Request_Http::getScheme` properly returns the HTTPS scheme in such situations.

### Manual testing scenarios (*)
1. Install a clean copy of OpenMage as usual
2. Install Symfony CLI and its [SSL certificates](https://symfony.com/doc/current/setup/symfony_server.html#enabling-tls)
3. Start the Symfony CLI local web server with `symfony server:start`
4. Configure OpenMage to use the `https://127.0.0.1:8000/` base URL for both secure and unsecure
5. Try to open the home page at https://127.0.0.1:8000/
6. Without this PR you'll get "Too many redirects" error, with this PR you'll properly get the home page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] Add yourself to contributors list

2021-11-04 13:00 UTC, elidrissidev submitted a review, later dismissed

2022-01-12 01:36 UTC, sreichel submitted a review, later dismissed

2022-01-12 08:34 UTC, ADDISON74 submitted a review, later dismissed

2022-01-12 10:29 UTC, luigifab reviewed
With PHP 8.1, if `$this->getServer('HTTPS')` return null, it will crash.
`strtolower(null)`: `PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated`

Not sure if this case can happen.

2022-02-15 23:13 UTC, Flyingmana requested changes
strtolower requires a string, but we could get a null here as of https://github.com/OpenMage/magento-lts/blob/b6cc7b24b078b721d6daa191a40bf5b1324e72df/app/code/core/Zend/Controller/Request/Http.php#L354

2022-02-16 10:19 UTC, Flyingmana approved these changes

2022-02-16 10:20 UTC, elidrissidev approved these changes

2022-02-16 10:37 UTC, merged