Sort ascending CMS Block list in Categories
OpenMage/magento-lts pull request #1925
Opened 2021-12-25 19:56 UTC by ADDISON74

This PR fixes the issue reported here #1678.

2021-12-25 23:01 UTC, fballiano approved these changes

2021-12-26 02:45 UTC, sreichel commented
Can't add review ...

```
POSThttps://github.com/OpenMage/magento-lts/pull/1925/review_comment/create
[HTTP/2 500 Internal Server Error 321ms
```

2021-12-26 14:31 UTC, sreichel requested changes
```suggstion
                ->setOrder('title', Varien_Data_Collection::SORT_ORDER_ASC)
```

2021-12-27 10:08 UTC, ADDISON74 commented
@sreichel - The proposal that you made by using Varien_Data_Collection :: SORT_ORDER_ASC instead of 'ASC' I did not find it in the OpenMage code. Through proposed PR I sought not to have any difference of approach between what exists and what I propose. Eventually both variants produce the same result.

2021-12-27 10:25 UTC, Flyingmana approved these changes

2021-12-27 10:25 UTC, merged