Remove white space for config values for #1852
OpenMage/magento-lts pull request #2020
Opened 2022-02-16 09:16 UTC by luigifab

### Description
I removed white space from config values for `OR` and `AND` (introduced with #1852).

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

2022-03-10 04:49 UTC, sreichel requested changes

2022-03-10 04:49 UTC, sreichel commented on app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php
> +                $likeCond = '(' . implode(' '.$separator.' ', $like) . ')';
```suggestion
                $likeCond = '(' . implode(' ' . $separator . ' ', $like) . ')';
```

2022-03-23 01:23 UTC, kiatng approved these changes

2022-03-23 04:59 UTC, sreichel approved these changes

2022-03-23 14:54 UTC, ADDISON74 approved these changes

2022-04-20 17:16 UTC, fballiano approved these changes

2022-04-20 20:24 UTC, merged