Fix xml validation problems
OpenMage/magento-lts pull request #2242
Opened 2022-06-20 11:30 UTC by fballiano

We're trying to introduce XML validation as a github workflow, the commonly used technique is running xmllit with something like:

`find . -type f -iname '*.xml' | xargs -I '{}' xmllint --noout '{}'`

problem is, xmllint is broken because our XMLs have a "name" variable in some places.

Since that variable was always replaced with "Magento" I figured to:
- change the Magento name in OpenMage
- hardcode the OpenMage name in the XMLs so that xmllint works without problems

### Fixed Issues (if relevant)
This PR is part of the fix for https://github.com/OpenMage/magento-lts/issues/1918

### Manual testing scenarios (*)

You've the command line in the task description.
Also check that APIs work.

2022-06-21 08:33 UTC, ADDISON74 submitted a review, later dismissed

2022-06-26 02:50 UTC, kiatng requested changes

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Api/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Api/etc/wsdl2.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
       <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Api/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/CatalogInventory/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Catalog/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Checkout/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Core/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Customer/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Directory/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Downloadable/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/GiftMessage/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Sales/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 02:50 UTC, kiatng commented on app/code/core/Mage/Tag/etc/wsdl.xml
>          <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Magento">
```suggestion
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:OpenMage">
```

2022-06-26 07:50 UTC, fballiano commented
@kiatng I think I commited all your suggestions, thanks!

2022-07-10 18:02 UTC, Flyingmana approved these changes

2022-07-10 18:05 UTC, ADDISON74 commented
If a value cannot be assigned to {{var wsdl.name}} then this manual change is absolutely necessary.

2022-07-10 18:08 UTC, tmewes approved these changes

2022-07-12 14:06 UTC, elidrissidev approved these changes

2022-07-12 14:11 UTC, merged

2023-01-03 10:51 UTC, Flyingmana commented
note: changing the schema name to OpenMage was breaking Integrations with external services (reported on a different place)