Added two indexes on sales_flat_order and sales_flat_order_item tables
OpenMage/magento-lts pull request #2447
Opened 2022-08-18 08:28 UTC by fballiano

This solution was already discussed and agreed in issue https://github.com/OpenMage/magento-lts/issues/384 I just created the PR into the Mage_Sales module since in 2022 I don't see the need for a new dedicated module for this specific task (as discussed in the previously linked issue).

2022-08-19 10:40 UTC, tobihille submitted a review, later dismissed

2022-08-19 11:21 UTC, ADDISON74 approved these changes

2022-08-23 12:58 UTC, tobihille submitted a review, later dismissed

2022-08-23 13:28 UTC, ADDISON74 approved these changes

2022-08-23 13:59 UTC, fballiano commented
tested on 1million sales_flat_order_items rows on my local machine and took only a few seconds (10ish, also considering that cache was cold) so I guess it will not create troubles even to big stores in production.

2022-08-25 13:13 UTC, ADDISON74 approved these changes

2022-09-18 14:26 UTC, ADDISON74 submitted a review, later dismissed

2022-09-18 18:05 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> +/* @var Mage_Sales_Model_Entity_Setup $installer */
```suggestion
/** @var Mage_Sales_Model_Entity_Setup $installer */
```

2022-09-18 18:05 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> + * @package     Mage_Sales
```suggestion
 * @category   Mage
 * @package    Mage_Sales
```

2022-09-18 18:06 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> +);
```suggestion
$keyList = $installer->getConnection()->getIndexList($installer->getTable('sales/order_item'));
if (!isset($keyList['IDX_SALES_FLAT_ORDER_ITEM_PRODUCT_ID'])) {
    $this->getConnection()->addIndex(
        $installer->getTable('sales/order_item'),
        'IDX_SALES_FLAT_ORDER_ITEM_PRODUCT_ID',
        ['product_id']
    );
}
```

2022-09-18 18:08 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> +}
```suggestion
if (!isset($keyList['IDX_SALES_FLAT_ORDER_CUSTOMER_EMAIL'])) {
    $installer->run("
        ALTER TABLE {$installer->getTable('sales/order')}
        ADD INDEX `IDX_SALES_FLAT_ORDER_CUSTOMER_EMAIL` (`customer_email` (15));
    ");
}
```

What is the correct syntax for using ```(`customer_email` (15))``` with `$this->getConnection()->addIndex()`)

2022-09-18 18:10 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> + * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
```suggestion
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
```

2022-09-21 23:15 UTC, sreichel commented on app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php
> +);
This seems not requierd.

2022-09-21 23:18 UTC, sreichel requested changes
Please check my suggestion ... when i reset version in `core_resource` table an run update again ...

```
Error in file: "/var/www/html/app/code/core/Mage/Sales/sql/sales_setup/upgrade-1.6.0.10-1.6.0.11.php" - SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'IDX_SALES_FLAT_ORDER_CUSTOMER_EMAIL'
```

2022-09-22 10:23 UTC, fballiano commented
it should be ok now

2022-09-22 20:09 UTC, sreichel approved these changes

2022-09-22 20:54 UTC, ADDISON74 approved these changes

2022-09-22 20:57 UTC, merged