Removed deprecated code from Mage_Rss
OpenMage/magento-lts pull request #2464
Opened 2022-08-21 15:40 UTC by fballiano

This PR removed all the deprecated (since M1 1.4) code from the Mage_Rss module.

I anyway enabled the RSS generation:
<img width="725" alt="Schermata 2022-08-21 alle 16 38 43" src="https://user-images.githubusercontent.com/909743/185798995-eeb74bea-f2c5-4857-926b-f3ca05fd13d6.png">

and the feed gets generated correctly, so the functionality didn't get broken after this PR:
<img width="643" alt="Schermata 2022-08-21 alle 16 39 54" src="https://user-images.githubusercontent.com/909743/185799037-780368ab-78e7-47f2-8bd5-06fd18e11efc.png">

2022-08-21 15:42 UTC, ADDISON74 approved these changes

2022-08-21 15:48 UTC, ADDISON74 approved these changes

2022-08-21 17:23 UTC, ADDISON74 approved these changes

2022-08-22 08:15 UTC, tobihille submitted a review, later dismissed

2022-08-22 11:29 UTC, tmewes approved these changes

2022-08-22 21:21 UTC, ADDISON74 approved these changes

2022-08-23 00:21 UTC, sreichel requested changes

2022-08-23 00:28 UTC, fballiano commented on app/code/core/Mage/Rss/Model/Mysql4/Order.php
> -}
The whole pr is because this code is unused so why keep the class if we remove all the rest. Or maybe i didnt understand your comment.

2022-08-23 20:17 UTC, sreichel commented on app/code/core/Mage/Rss/Model/Mysql4/Order.php
> -}
Isn't it possible that 3rd party code relies on this classes? Maybe i got i wrong ...

2022-08-28 20:03 UTC, closed without merging

2022-08-28 20:03 UTC, fballiano commented
sorry, i'll have to recreate this