Added new useful columns in products tab in category view
OpenMage/magento-lts pull request #2713
Opened 2022-11-16 11:57 UTC by dbachmann

### Description (*)
Sometimes when you work in the category view in backend it is necessary to edit a product. It was not possible to edit a product from the products tab in category. To improve usability in backend I added two more columns: One with the current product status and the other provides an edit link which opens the desired product in a popup. 

![category_view_be](https://user-images.githubusercontent.com/1921769/202174661-da76f72c-9494-4c71-9215-5a56e5e41d03.JPG)

### Manual testing scenarios (*)
1. Go to categories
2. Open a category 
3. Open products tab
4. Click on edit

2023-04-05 10:14 UTC, matteotestoni submitted a review, later dismissed

2023-04-05 10:30 UTC, ADDISON74 commented
@luigifab proposed something similar here with more futures #1379.

PS - today the number of opened PRs decreased bellow 100. Around 25 of them will close opened issues.

2023-05-12 22:42 UTC, fballiano commented
fixed conflict

2023-05-12 22:56 UTC, fballiano commented
rebased and reformatted arrays to short syntax

2023-05-12 23:08 UTC, fballiano submitted a review, later dismissed
I've removed the popup window but I think this PR is useful and should be merged

2023-05-15 14:05 UTC, dbachmann commented
@fballiano So, when someone wants to edit a product from the category view, it will open in the same window?

2023-05-15 14:08 UTC, fballiano commented
you can press "shift" when you click and it opens in a new tab/windw. modern accessibility (as far as I know) says the GUI shouldn't decide the behavior instead of the user.
Also I don't think there are other places where the backend opens new windows, I may be wrong on that but I've never seen it in my daily work.

2023-05-16 10:06 UTC, dbachmann commented
@fballiano When you edit a simple product in a configurable product a pop up opens as well ;)

2023-05-16 12:37 UTC, fballiano commented
I've removed it while I was rebasing it because that's what I believe, I wouldn't want to have anything open a new window actually

2024-02-29 09:01 UTC, fballiano commented
@ADDISON74 what do you think about this one?

2024-02-29 13:28 UTC, ADDISON74 commented
@fballiano - I have to make a comparison with #1379. It's been a while since I last saw them analyzed. My opinion that both changes are useful. Many times I have added products using the category grid and I have not had the opportunity to see if the product is Enabled or Disabled. In addition, if I wanted to edit it to change the status, I had to open a new window and take several steps. @luigifab's version also brought an mandatory change, the issue with the position column and deselecting the row.

2024-02-29 14:59 UTC, fballiano commented
I see, but it seems to me that this specific one could be merged, asking you since you checked a looot of PRs about grids and columns

2024-03-02 18:47 UTC, ADDISON74 commented
@fballiano - We will limit this PR strictly to the columns and their position in the table. I have identified a few problems that I will present in detail these days.

2024-03-03 09:56 UTC, ADDISON74 commented
**My comments related to this PR are the following**

1 - The positioning of the columns in this product grid must be the same as the ones in the **Related**, **Up-sells**, **Cross-sells** grids, which can be found in the product editing page. A first requested change, the **Status** column must be placed to be next after the **Name** column.

![status](https://github.com/OpenMage/magento-lts/assets/8360474/c8250f55-c9fa-4eb4-a4ca-aab5c840f9ab)

2 - Not only the **Status** must be added as a column in this grid, but also other columns that are absolutely essential when adding products directly to the category page and that make work more efficient. Similar to the grids mentioned in point 1, **Type**, **Attribute Set Name**, **Visibility** are important and must be added. A product should not be searched only by name.

3 - This is an editable grid. If the **[Save]** button is not clicked before the **Edit** link is used, all the changes made in that page, not only in the grid (product addition/removal, position) are lost. In addition, there is no warning icon that you must save your work. As it is now, the voluntary or involuntary click of the **Edit** link loads the product editing page in the same window, at which point all the changes made are lost. I read your comments, the decision to remove the initial code was in a 1 to 1 situation. My opinion is that we should not force the users to hold down the Shift key to open a new window. Firstly, that they don't know about it, secondly, that they don't do it out of error, fatigue. The situation is similar to other cases of editing in a page where changes behind must be kept, such as Associated Products and where the Magento team has taken this into account. Adding this action must follow the existing behavior in OpenMage and this means to open the editing in another window.

4 - In the window that opens, it would be elegant to keep the behavior of the buttons in the case of editing the Associated Products. There are only three buttons in the window, see bellow. I haven't studied how it could be done, but I think it can be solved in a new Settings.php file that is added to the same directory.

![buttons](https://github.com/OpenMage/magento-lts/assets/8360474/8429b29f-1ba5-4008-ad3b-2a50ed696196)

5 - Regarding the **Status** column, the line ```'id' =>``` I haven't found it in other grids. It can be removed.

2024-03-03 11:14 UTC, ADDISON74 commented on app/code/core/Mage/Adminhtml/Block/Catalog/Category/Tab/Product.php
> +        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
```suggestion
        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
        $collection->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner');
```

2024-03-03 11:25 UTC, ADDISON74 requested changes

2024-03-03 11:25 UTC, ADDISON74 commented on app/code/core/Mage/Adminhtml/Block/Catalog/Category/Tab/Product.php
I didn't want to edit the file and create a commit. This change makes the grid the same with the ones in **Related**, **Up-sells** and **Cross-sells**. 

For the **Price** column the width was set to 1 ```'width'     => '1',```. It should be removed as I did bellow.

```php
protected function _prepareColumns()
    {
        if (!$this->getCategory()->getProductsReadonly()) {
            $this->addColumn('in_category', [
                'header_css_class' => 'a-center',
                'type'      => 'checkbox',
                'name'      => 'in_category',
                'values'    => $this->_getSelectedProducts(),
                'align'     => 'center',
                'index'     => 'entity_id'
            ]);
        }
        $this->addColumn('entity_id', [
            'header'    => Mage::helper('catalog')->__('ID'),
            'sortable'  => true,
            'width'     => '60',
            'index'     => 'entity_id'
        ]);
        $this->addColumn('name', [
            'header'    => Mage::helper('catalog')->__('Name'),
            'index'     => 'name'
        ]);

        $this->addColumn('type', [
            'header'    => Mage::helper('catalog')->__('Type'),
            'width'     => 100,
            'index'     => 'type_id',
            'type'      => 'options',
            'options'   => Mage::getSingleton('catalog/product_type')->getOptionArray(),
        ]);

        $sets = Mage::getResourceModel('eav/entity_attribute_set_collection')
            ->setEntityTypeFilter(Mage::getModel('catalog/product')->getResource()->getTypeId())
            ->load()
            ->toOptionHash();

        $this->addColumn('set_name', [
            'header'    => Mage::helper('catalog')->__('Attrib. Set Name'),
            'width'     => 130,
            'index'     => 'attribute_set_id',
            'type'      => 'options',
            'options'   => $sets,
        ]);

        $this->addColumn('status', [
            'header'    => Mage::helper('catalog')->__('Status'),
            'width'     => 90,
            'index'     => 'status',
            'type'      => 'options',
            'options'   => Mage::getSingleton('catalog/product_status')->getOptionArray(),
        ]);

        $this->addColumn('visibility', [
            'header'    => Mage::helper('catalog')->__('Visibility'),
            'width'     => 90,
            'index'     => 'visibility',
            'type'      => 'options',
            'options'   => Mage::getSingleton('catalog/product_visibility')->getOptionArray(),
        ]);


        $this->addColumn('sku', [
            'header'    => Mage::helper('catalog')->__('SKU'),
            'width'     => '80',
            'index'     => 'sku'
        ]);
        $this->addColumn('price', [
            'header'    => Mage::helper('catalog')->__('Price'),
            'type'  => 'currency',
            'currency_code' => (string) Mage::getStoreConfig(Mage_Directory_Model_Currency::XML_PATH_CURRENCY_BASE),
            'index'     => 'price'
        ]);
        $this->addColumn('position', [
            'header'    => Mage::helper('catalog')->__('Position'),
            'width'     => '1',
            'type'      => 'number',
            'index'     => 'position',
            'editable'  => !$this->getCategory()->getProductsReadonly()
            //'renderer'  => 'adminhtml/widget_grid_column_renderer_input'
        ]);
        $this->addColumn('action', [
            'header'    => Mage::helper('catalog')->__('Action'),
            'width'     => '50px',
            'type'      => 'action',
            'getter'    => 'getId',
            'actions'   => [
                [
                    'caption'   => Mage::helper('catalog')->__('Edit'),
                    'id'        => 'editlink',
                    'field'     => 'id',
                    'onclick'  => 'event.stopPropagation()',
                    'url'       => [
                        'base'      => 'adminhtml/catalog_product/edit',
                        'params'    => ['store' => $this->getRequest()->getParam('store')],
                    ]
                ],
            ],
            'filter' => false,
            'sortable' => false,
            'index' => 'stores',
        ]);

        return parent::_prepareColumns();
    }
```

The approach for the **Edit** action will be discussed later.

2024-03-03 12:12 UTC, ADDISON74 commented
This should be the **Action** column. ```popup => 1``` enables only three buttons in the window [Close Window], [Reset] and [Save], like for the Associated Products.

```php
        $this->addColumn('action', [
            'header'    => Mage::helper('catalog')->__('Action'),
            'width'     => '50px',
            'type'      => 'action',
            'getter'    => 'getId',
            'actions'   => [
                [
                    'caption'   => Mage::helper('catalog')->__('Edit'),
                    'url'       => [
                        'base'      => 'adminhtml/catalog_product/edit',
                        'params'    => [
                            'store' => $this->getRequest()->getParam('store'),
                            'popup' => 1
                        ],
                    ],
                    'field'     => 'id',
                    'onclick' => 'popWin(this.href,\'_blank\',\'width=1024,height=750,resizable=1,scrollbars=1\');return false;',
                ],
            ],
            'filter' => false,
            'sortable' => false,
            'index' => 'stores',
        ]);
```

There is an issue after saving the product. The bellow window doesn't have the same behavior like the one for Associated Products. The window is not closing automatically and the [Close Window] button it is not working. The error in console is 

```console
Uncaught TypeError: Cannot read properties of undefined (reading 'updateProduct')
    at addProduct (1ae108f468e971e091309d629583f5aa/:133:44)
    at 1ae108f468e971e091309d629583f5aa/:151:1
```

![window](https://github.com/OpenMage/magento-lts/assets/8360474/18f472c3-6cb7-4b9c-baa2-b2bdf6c16606)

2024-03-03 21:51 UTC, ADDISON74 commented
I have updated this PR. Now the grid has the same format as those in **Related Products / Up-sells / Cross-sells**.

The unsolved problem is still the editing action:

1 - Editing a product must be done in a new window, opened by clicking on the link and having the same behavior as when the associated products are edited.

2 - There must be 3 buttons in the window. After pressing the [Save] button, the window either closes automatically or by pressing the [Close Window] button, exactly the same behavior as when the associated products are edited.

3 - Editing a product should update the grid. For example, when the status of the product is changed by saving, the change does not occur in the grid. A click on other category then coming back to the initial category will make visible the changes.

2024-04-25 18:13 UTC, fballiano commented
I don't like the opening of new windows because accessibility mandates that it has to be the user to decide if they want the same window, a new tab or a new window.

but since it's already used in configurable products, I've reverted my change and implemented the popup parameter as requested by @ADDISON74 so have the same behavior (and same window name) of the configurable products management page.

since everything seems to be working fine and there were already quite some tests, if all workflows are green I'll merge it.

2024-04-25 18:13 UTC, fballiano approved these changes

2024-04-25 18:19 UTC, fballiano commented
actually... no... adding the popup parameter has this behavior now

<img width="854" alt="Screenshot 2024-04-25 alle 19 18 56" src="https://github.com/OpenMage/magento-lts/assets/909743/45cafcd2-04eb-45f8-95f9-fd9a017ff225">

2024-04-25 18:34 UTC, fballiano commented
this is because the popup parameter calls some specific javascript code for configurables:

<img width="1125" alt="Screenshot 2024-04-25 alle 19 20 14" src="https://github.com/OpenMage/magento-lts/assets/909743/e6b7d299-deb1-48c5-8862-f481441b03ba">

I' ve now patched the js in order to not have the js error when trying to close the windows (tested both here and configurable and both still work) but I wouldn't develop all this new javascript just to refresh the grid, it seems too much for this small functionality

2024-04-25 19:09 UTC, fballiano commented
I made the reload work yeah! so all of the points listed by @ADDISON74 should be solved

2024-04-25 19:09 UTC, fballiano approved these changes

2024-04-25 21:26 UTC, ADDISON74 commented
Let me test again to provide you a feedback before approving. Many thanks for your patience in solving that js error.

This PR will be a great new feature.

2024-04-26 08:42 UTC, ADDISON74 approved these changes
I checked this PR and all my previous reported issues were resolved. Editing a product opens a new window, there are 3 buttons as in the case of associated products, if the status of the product is changed and the [Save] button is pressed, the status is immediately changed in the grid on the category page. The editing window closes automatically if the button is not pressed. I found no errors in the console. There have been similar paid or free versions in the past, but none offered what was implemented here.

@fballiano - thank you for completing this PR.

2024-04-26 08:46 UTC, fballiano commented
one more on the road to zero PRs, let's go!

2024-04-26 08:47 UTC, merged