Backported #1600: removed M1 "default" themes
OpenMage/magento-lts pull request #2863
Opened 2022-12-29 09:49 UTC by fballiano

In the effort to reduce the differences between v19 and v20 and cleaup our codebase as much as possible, this PR backports #1600, the removal of the old and unmaintained `app/design/frontend/default`.

It was already done in v20 but with this PR we port it to v19.

Not to create problems to users who may use those themes, I created a backward compatibility module here: https://github.com/OpenMage/module-m1-default-themes which can be installed via composer (the README was updated with this information).

Related PR: https://github.com/OpenMage/magento-lts/pull/1600

2022-12-29 09:49 UTC, fballiano commented
@sreichel @Flyingmana could you create the packagist entry for https://github.com/OpenMage/module-m1-default-themes? I think I can't do it. Thanks!

2022-12-29 11:04 UTC, ADDISON74 commented
A small observation related to the name of the repository. m1 is not found in the other recently created ones. Maybe you should establish a rule about this. module-mage-poll, module-mage-tag, module-mage-pagecache, module-mage-backup are fine in my opinion.

2022-12-29 11:10 UTC, fballiano commented
it is true, I used that naming because it's not really a module (since it's a group of themes) and I didn't want to name it "default themes" because it could be misleading, since these are the old "m1 default themes", I know it kinda sucks but I think it's the most understandable for this specific content. 🥺

2022-12-29 21:23 UTC, sreichel commented
`openmage/frontend-legacy-themes`?

2022-12-29 21:29 UTC, fballiano commented
I know it's not a module but wouldn't it be easier (to keep everything organized) to have the "module-" prefix?

2022-12-29 21:41 UTC, sreichel commented
Mhhh. A "theme-"prefix? Dont know.

2022-12-29 21:42 UTC, fballiano commented
mmmm nah

maybe openmage/legacy-frontend-themes?

2022-12-29 22:14 UTC, fballiano commented
Changed repo name ;-)

@sreichel @Flyingmana could you create the packagist entry for https://github.com/OpenMage/legacy-frontend-themes?

2022-12-29 22:43 UTC, sreichel commented
Done.

Wanted to do the [same](https://github.com/sreichel/openmage-bc-legacy-themes), but did not start ...

- Should we split themes into smaller packages? The modern theme is used for some shops a know - or custom theme are base on it, but is it worth?

- We should remember that [symlinks are not allowed anymore](https://magento.stackexchange.com/a/176969/46249). How to solve this?
  - set deploy-strategy to "copy" for this package, as i did it for dev-shell scripts?
  - leave it to the user to change delpoy-strat? Needs some info in README and maybe [mse-sv3n/allowsymlinks](https://packagist.org/packages/mse-sv3n/allowsymlinks) as composer requirement?

2022-12-29 23:06 UTC, ADDISON74 commented
I agree to cut slices from the code and taking them to repositories, but I think they should be as targeted (important ones and not too many). For years all changes were made in this repository and people used to report issues and propose PRs here. We have to avoid scattering them.

2022-12-29 23:12 UTC, fballiano commented
I wouldn't split them in single repos, is seems to much for such old code.

deploy strategy mmmm that's a good point, maybe force it to "copy" is the right choice, if you already did it for the dev scripts then it would be coherent :-)

2022-12-29 23:19 UTC, fballiano commented
@sreichel how did you force the deploy strategy? I can't find anything the composer.json (of the dev-* repos)

2022-12-29 23:20 UTC, sreichel commented
```
        "magento-deploystrategy-overwrite": {
            "openmage/dev-copyright": "copy",
            "openmage/dev-translations": "copy"
        },
```

2022-12-29 23:30 UTC, fballiano commented
ah ok ok, i thought it was in the external repos, done ;-)

2022-12-29 23:37 UTC, sreichel commented
> We have to avoid scattering them.

@ADDISON74 totally right (atm), but it only removes old templates from v19 to have less differences between branches. Moving (dead) code to its own repo is just to keep BC.

@fballiano how about release-builder? v19 releases should include old template files.

2022-12-29 23:38 UTC, sreichel commented
> ah ok ok, i thought it was in the external repos, done ;-)

Did not test it, but i doubt it works.

2022-12-30 00:36 UTC, sreichel commented
@fballiano should we wait with v1 release until #2847 is merged?

Before i removed the other modules i tried to fix all related phpstan issues, to leave it as clean as possible.

2022-12-30 11:30 UTC, fballiano commented
if you want. I wouldn't care about some piece of code nobody uses since a gazilion years but as you prefer.

2022-12-30 20:52 UTC, sreichel commented
> if you want. I wouldn't care about some piece of code nobody uses since a gazilion years but as you prefer.

yep. its one PR to have it also cleand up.

> ah ok ok, i thought it was in the external repos, done ;-)

This need to be added to repos README. When you use `composer require openmage/magento-lts` the deploy-strat hast to be set in projects composer.json (too)

2023-01-02 09:04 UTC, fballiano commented
> This need to be added to repos README. When you use `composer require openmage/magento-lts` the deploy-strat hast to be set in projects composer.json (too)

@sreichel we need to state that users have to add the "apply patch directive" to their composer repo?

2023-01-02 09:10 UTC, fballiano commented
> This need to be added to repos README. When you use `composer require openmage/magento-lts` the deploy-strat hast to be set in projects composer.json (too)

@sreichel added info to https://github.com/OpenMage/legacy-frontend-themes README ;-)

2023-01-02 19:27 UTC, sreichel commented
Its enough to set it only for this module ...

```
"magento-deploystrategy-overwrite": {
    "openmage/legacy-frontend-themes": "copy",
},
```

- a link to stackexchange could be added for some more information
- also explain 2nd method that allows symlinks (on own risk)?

2023-01-02 19:58 UTC, Flyingmana requested changes
Blocking it as there are for sure Magento1 themes out there, which are build on top of them, and v19 is intended to be an easy target to move from M1 to OpenMage.

So the possible ways forward to have this merged:
1. it has to be included in the release download
2. there needs to be a finished and accepted RFC which allows to get major breaking changes into V19

2023-01-02 20:00 UTC, sreichel commented
> it has to be included in the release download

:+1: Already mentioned this  somewhere.

2023-01-03 08:59 UTC, fballiano commented
@sreichel ok perfect I've fixed the https://github.com/OpenMage/legacy-frontend-themes/blob/main/README.md file and we already have magento-deploystrategy-overwrite in our main repo, so that should cover it :-)

@Flyingmana you could partecipate in the discussion instead of vetoing me. I don't recall force commit something regardless of other people approval so I don't feel there's the need to block me. Other maintainers could have different opinions, they should be heard and valued and that is not possible when there's a veto.

**I'll work to make a different release builder for the 2 branches** but let's be real: who uses v19 without composer is for sure extracting the zipfile on top of the existing project, so if some files are missing is really changes anything.

2023-01-03 09:05 UTC, Flyingmana commented
> @Flyingmana you could partecipate in the discussion instead of vetoing me. I don't recall force commit something regardless of other people approval so I don't feel there's the need to block me. Other maintainers could have different opinions, they should be heard and valued and that is not possible when there's a veto.

It is more a message for the other maintainers who might have overlooked this to be a requirement and not just something which can be discussed away in a Ticket/PR.

2023-01-03 09:13 UTC, tmotyl commented
"but let's be real: who uses v19 without composer is for sure extracting the zipfile on top of the existing project, so if some files are missing is really changes anything."

@fballiano I'm ok with moving these old templates out of repo, however, please note that a common deployment pattern (and a best practice before composer) for openmage is to "build"/prepare app code in a fresh folder and then switch server webroot (or change symlink). 
So missing files are an issue, and require changes in the deployment process.
The flow is true for unzipping archives and cloning the github repo (using git submodule, or directly).

2023-01-03 09:22 UTC, fballiano commented
The "release builder" workflow is now modified in order to add openmage/legacy-frontend-themes back in the release zipfile only for v19.

please verify here:
- https://github.com/fballiano/openmage/releases/tag/v19.test.5 with the themes
- https://github.com/fballiano/openmage/releases/tag/v20.test.5 without the themes

with the modification we can add back https://github.com/OpenMage/magento-lts/pull/2811 pretty easily if you want to.

2023-01-03 22:24 UTC, fballiano commented
Merged and fixed conflict with composer.lock

2023-01-04 04:32 UTC, sreichel commented
> It is more a message for the other maintainers who might have overlooked this to be a requirement and not just something which can be discussed away in a Ticket/PR.

@Flyingmana its you having overlooked related PRs.

Adding this changes to downloadable release was mentioned before. Adding things to docs is something we frequently do.

2023-01-12 16:50 UTC, fballiano commented
fixed conflicts, it should be ready again.

2023-01-12 17:06 UTC, fballiano commented
mmm i don't know what phpstan is complaining about cause this PR doesn't touch any logic

2023-01-12 19:45 UTC, sreichel commented
@fballiano i dont know why, but this error comse and goes .... counterpart e.g. here:

https://github.com/fballiano/openmage/actions/runs/3784755427/jobs/6434331180

2023-01-12 20:28 UTC, ADDISON74 commented
Based on the error it seems the ZF1-Future is missing in that installation.

```php
Error: Call to an undefined method Zend_Db_Adapter_Abstract::getCheckSql().
```

2023-01-12 20:37 UTC, sreichel commented
`getCheckSql()` does not exist in `Zend_Db_Adapter_Abstract`, but in `Varien_Db_Adapter_Interface` .... it's a bit tricky

2023-01-12 20:38 UTC, sreichel commented
@fballiano to pass checks, please update baseline file.

2023-01-12 20:54 UTC, ADDISON74 commented
Maybe a new line in phpstan.dist.baseline.neon is needed. There are already two references inside related to the getCheckSql() method.

2023-01-12 21:01 UTC, fballiano commented
mmmm when I do

```
fab@MBP-Fab ~/P/openmage (backport_1600) [1]> /usr/local/opt/php@7.3/bin/php vendor/bin/phpstan --generate-baseline
Note: Using configuration file /Users/fab/Projects/openmage/phpstan.dist.neon.
 4350/4350 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [WARNING] Baseline generated with 0 errors.                                                                            
           Some errors could not be put into baseline. Re-run PHPStan and fix them.                                     

```

😱

2023-01-12 21:20 UTC, sreichel commented
Please add baseline filename ...

```
vendor/bin/phpstan -b phpstan.dist.baseline.neon
```

2023-01-12 21:37 UTC, fballiano commented
done! let's see :-D

2023-01-12 21:51 UTC, fballiano commented
I guess the generated baseline was not the best 😅

2023-01-12 21:53 UTC, sreichel commented
Already wondered about so many changes ... it should only fix the checkSql error ....?!?

2023-01-12 21:55 UTC, fballiano commented
I used

`/usr/local/opt/php@7.3/bin/php vendor/bin/phpstan --generate-baseline=phpstan.dist.baseline.neon`

cause without the "=" was giving me an error, dunno :-(

2023-01-12 21:58 UTC, sreichel commented
Mhh, i always use shortcut `-b` (w/o `=`)

2023-01-12 21:58 UTC, fballiano commented
if I just copied your command I got an error :-\

2023-01-13 22:04 UTC, ADDISON74 approved these changes

2023-01-16 10:25 UTC, sreichel commented
Can this wait a bit? (https://github.com/OpenMage/magento-lts/pull/2863#issuecomment-1367661350)

2023-01-16 11:15 UTC, fballiano commented
for sure. I don't care about those mega old themes so I wouldn't fix them but we don't need to remove them urgently :-)

2023-01-19 02:10 UTC, sreichel commented
Same for Mage_PageCache or Mage_Backup ...

Instead of removing "Components" from and put them into a new repo, we can follow another approach ... 

- split code into openmage-modules
- have all code in main-repo

See: https://github.com/symplify/monorepo-builder

2023-01-19 09:21 UTC, fballiano commented
dunno why the "check modified files" fails but composer lock is ok

```
fab@MBP-Fab ~/P/openmage (backport_1600)> /usr/local/opt/php@7.3/bin/php /usr/local/bin/composer validate --strict
you may want to add the packages.firegento.com repository to composer.
add it with: composer.phar config -g repositories.firegento composer https://packages.firegento.com
you may want to add the packages.firegento.com repository to composer.
add it with: composer.phar config -g repositories.firegento composer https://packages.firegento.com
./composer.json is valid

```

2023-02-07 20:48 UTC, fballiano commented
@elidrissidev @kiatng @ADDISON74 guys can we move this one forward or should I close it?

2023-02-07 21:00 UTC, elidrissidev approved these changes

2023-02-07 22:20 UTC, ADDISON74 commented
Please keep it open for a while. I need to revise all those files to avoid any mistakes.

2023-02-08 01:44 UTC, kiatng approved these changes

2023-02-08 09:00 UTC, merged

2023-02-08 09:00 UTC, fballiano commented
thanks guys, merged and ported to 20.0