Added instructions for cash on delivery
OpenMage/magento-lts pull request #3302
Opened 2023-06-05 18:59 UTC by luigifab

### Description

Like for `banktransfer` orders, this PR add instructions for `cashondelivery` orders.

Moreover, this PR add a second configuration for instructions for orders.
So you can have two texts, one for quotes, and another one for orders.

If I'm not wrong, added behaviour for `cashondelivery` this is exactly the same as for `banktransfer`.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [x] Add yourself to contributors list

2023-07-04 10:10 UTC, empiricompany approved these changes

2023-07-07 22:28 UTC, ADDISON74 commented
By default both **Bank Transfer Payment** and **Cash On Delivery Payment** have **Instructions fields**. See bellow

![screenshot_4](https://github.com/OpenMage/magento-lts/assets/8360474/903d15f1-f524-4c2e-a2fe-029231dae6b2)

If these fields are filled in we can see them listed in checkout. 

![screenshot_3](https://github.com/OpenMage/magento-lts/assets/8360474/a2821c92-281a-469a-bc1d-ae22ec972497)

This PR comes to add one more field for both payments. What is the purpose?

2023-07-10 07:51 UTC, empiricompany commented
by default, cash on delivery instructions are printend only in the checkout and not in the order details/email. 
This PR adds a separate field "istructions_order", but perhaps it's better to keep a single field.

config
![immagine](https://github.com/OpenMage/magento-lts/assets/5071467/4fb6b7d5-3661-49c1-8b36-31688ad8cf33)

frontend order detail
![immagine](https://github.com/OpenMage/magento-lts/assets/5071467/3df20684-c82b-445d-9632-3a06230262dc)

backend order detail
![immagine](https://github.com/OpenMage/magento-lts/assets/5071467/bd9eadc4-985e-4cb1-ab75-156e2cf7a445)

2023-07-10 07:52 UTC, fballiano commented
I also think, at first glance, that a single field would be easier

2023-07-10 07:53 UTC, empiricompany requested changes
I don't see a reason to add a second field; I would keep a single field for the instructions.

2023-07-10 09:21 UTC, ADDISON74 commented
The conclusion is correct, there is no need for another field for these payment methods. If the COD information is not displayed on the order editing page and in the email messages sent to the buyer, then the change must be made here.

[OFF TOPIC]
For those who are interested, I've been using an extension for a long time that allows to have my own payment methods, in addition to the already existing ones.

https://github.com/mobweb/MobWeb_MultipleBankTransferPaymentMethods

2023-07-12 17:43 UTC, fballiano commented
@ADDISON74 what about we add this multiple banktransfer to the core? and multiple flatrate too? which I've always had to add anyway to all my customers?

2023-07-12 17:47 UTC, fballiano commented
@luigifab would it be ok with you to modify the PR and use the same "instructions" field in the order too?

2023-07-12 22:04 UTC, ADDISON74 commented
@fballiano

1. That extension is very useful for custom payment methods. Implicitly it comes with its section names in the Backend. 

![btp](https://github.com/OpenMage/magento-lts/assets/8360474/f04fc8cc-2bac-465c-98ba-b115e8a12ffc)

I changed their name because they are not "Bank Transfer Payment" in my case. It can be added into the OpenMage core because it is useful. As section names I would change to "Custom Payment Method 1", "Custom Payment Method 2". I would reduce the number of them to just  two.

2. If the author of a PR does not respond to the request within a reasonable time  that PR can be modified by those who have editing rights. An RFC addendum could be useful.

2023-07-13 07:32 UTC, empiricompany commented
> @ADDISON74 what about we add this multiple banktransfer to the core? and multiple flatrate too? which I've always had to add anyway to all my customers?

Personally, I disagree with adding it to the core. I would leave it among the recommended modules. 
But what is the policy for this type of decision? Do I have any voting rights? Otherwise, I won't interfere in these matters anymore..

2023-07-13 07:33 UTC, fballiano commented
to add it to the core, there's the need of a PR, which needs votes :-) so you have the right to your opinion as everybody else :-)

2023-07-13 11:43 UTC, ADDISON74 commented
BTW MobWeb has a lot of nice extensions, some of them I am using in production for many years

https://github.com/mobweb?page=1&tab=repositories

2023-07-13 12:32 UTC, empiricompany commented
> BTW MobWeb has a lot of nice extensions, some of them I am using in production for many years
> 
> https://github.com/mobweb?page=1&tab=repositories

wow useful resource!

2023-10-21 13:26 UTC, luigifab commented
We are using one text for quotes and another one for orders, so if I update the PR, I'm going to have more work.

2024-02-21 23:08 UTC, fballiano commented on app/code/core/Mage/Payment/Block/Info/Cashondelivery.php
> + * @copyright  Copyright (c) 2023 The OpenMage Contributors (https://www.openmage.org)
```suggestion
 * @copyright  Copyright (c) 2024 The OpenMage Contributors (https://www.openmage.org)
```

2024-02-21 23:09 UTC, fballiano commented on app/code/core/Mage/Payment/Model/Method/Banktransfer.php
> +            $amount = $order->formatPriceTxt($order->getData('grand_total'));
is it possible for this to be null and thus trigger a null parameter warning?

2024-02-21 23:10 UTC, fballiano commented on app/design/frontend/base/default/template/payment/info/cashondelivery.phtml
> + * @copyright   Copyright (c) 2023 The OpenMage Contributors (https://www.openmage.org)
```suggestion
 * @copyright   Copyright (c) 2024 The OpenMage Contributors (https://www.openmage.org)
```

2024-02-21 23:30 UTC, fballiano commented
@luigifab I see there's a fallback between instructions_order and instructions, which makes be be ok with the PR, although I don't like 100% it doesn't mean I shouldn't approve it.

question: when do the "instructions order" get displayed? on the frontend? in emails? because the name "instructions order" is a bit unclear, maybe we could make it a bit cleared?

2024-04-09 16:49 UTC, luigifab commented
Orders instructions are displayed when orders are placed: so in email, in frontend, in backend.

And when there are no orders instructions, quotes instructions are used. There are displayed everywhere: onepage checkout, email, backend, frontend.

2024-04-26 18:32 UTC, fballiano commented
> Orders instructions are displayed when orders are placed: so in email, in frontend, in backend.
> 
> And when there are no orders instructions, quotes instructions are used. There are displayed everywhere: onepage checkout, email, backend, frontend.

ok it's now clear, I think that maybe the wording should explain it a bit more

for example the string "instructions on order", @ADDISON74 do you have a clearer wording for that or you think it's easy to understand?

also, below instructions and instructions_order we should have comments explaining what they are for and how the system uses it, @ADDISON74 a couple of easy sentences come to your mind?

2024-07-29 17:06 UTC, closed without merging

2024-07-29 17:28 UTC, ADDISON74 commented
@luigifab - any reasons for closing this PR?