Deprecated `createEntityTables()` in `Mage_Eav_Model_Entity_Setup`.
OpenMage/magento-lts pull request #3628
Opened 2023-11-05 03:01 UTC by kiatng

### Description (*)
The function `createEntityTables()` isn't reference in the core, see [search result](https://github.com/search?q=repo%3AOpenMage%2Fmagento-lts+createEntityTables&type=code). As reported in issue #3626, the function does not add the required unique indexes. I propose to deprecate the function as it is not used in the core.

### Related Pull Requests
Issue #3626.

2023-11-05 22:12 UTC, ADDISON74 requested changes

2023-11-05 22:12 UTC, ADDISON74 commented on app/code/core/Mage/Eav/Model/Entity/Setup.php
> +     * @deprecated Missing unique undexes. To create custom EAV tables, refer to the core:
"undexes" => "indexes"

2024-01-27 18:15 UTC, luigifab approved these changes

2024-01-30 22:47 UTC, sreichel approved these changes

2024-01-30 22:49 UTC, fballiano approved these changes

2024-01-30 22:50 UTC, merged