Fixes table prefix when using `-d` and `-s` flag
OpenMage/magento-lts pull request #3749
Opened 2024-01-22 21:12 UTC by sreichel

### Description (*)

### Related Pull Requests

When using sh/ddev command `openmage-install` with `-d` flag (use default values) combined with `-s` (sample data) table prefix is set wrong and you'll no sample data.

### Manual testing scenarios (*)
1.  sh/ddev `openmage-install -s -d -k`

2024-01-27 03:50 UTC, sreichel commented
@ADDISON74 requst review knowing you use ddev.

2024-01-31 21:22 UTC, ADDISON74 commented
I did a checkout on this PR. Here is the Terminal window content after running the command

```ddev openmage-install -s -d -k```

```php
ubuntu@DESKTOP-GBHMUPN:~/openmage$ ddev openmage-install -s -d -k
OpenMage is already installed. Delete local.xml and drop the database? [y/N] y
Uncompressing Sample Data...
Copying Sample Data into the OpenMage directory...
Importing Sample Data into the database...
PHP Fatal error:  Uncaught Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:510
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(318): Mage_Core_Model_Config->getCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}

Next Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:534
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(326): Mage_Core_Model_Config->releaseCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}
  thrown in /var/www/html/app/code/core/Mage/Core/Model/Config.php on line 534

Fatal error: Uncaught Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:510
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(318): Mage_Core_Model_Config->getCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}

Next Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:534
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(326): Mage_Core_Model_Config->releaseCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}
  thrown in /var/www/html/app/code/core/Mage/Core/Model/Config.php on line 534
Failed to run openmage-install -s -d -k: exit status 255
```

If I am reloading the Frontend page in the browser I am getting this content

```php
Fatal error: Uncaught Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:510 Stack trace: #0 /var/www/html/app/code/core/Mage/Core/Model/App.php(436): Mage_Core_Model_Config->getCacheSaveLock() #1 /var/www/html/app/code/core/Mage/Core/Model/App.php(347): Mage_Core_Model_App->_initModules() #2 /var/www/html/app/Mage.php(743): Mage_Core_Model_App->run(Array) #3 /var/www/html/index.php(56): Mage::run('', 'store') #4 {main} Next Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:534 Stack trace: #0 /var/www/html/app/code/core/Mage/Core/Model/App.php(448): Mage_Core_Model_Config->releaseCacheSaveLock() #1 /var/www/html/app/code/core/Mage/Core/Model/App.php(347): Mage_Core_Model_App->_initModules() #2 /var/www/html/app/Mage.php(743): Mage_Core_Model_App->run(Array) #3 /var/www/html/index.php(56): Mage::run('', 'store') #4 {main} thrown in /var/www/html/app/code/core/Mage/Core/Model/Config.php on line 534
```

I checked out the main branch and this is the content of the Terminal window

```php
ubuntu@DESKTOP-GBHMUPN:~/openmage$ ddev openmage-install -s -d -k
Uncompressing Sample Data...
Copying Sample Data into the OpenMage directory...
Importing Sample Data into the database...
PHP Fatal error:  Uncaught Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:510
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(318): Mage_Core_Model_Config->getCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}

Next Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:534
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(326): Mage_Core_Model_Config->releaseCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}
  thrown in /var/www/html/app/code/core/Mage/Core/Model/Config.php on line 534

Fatal error: Uncaught Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:510
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(318): Mage_Core_Model_Config->getCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}

Next Error: Call to a member function fetchOne() on bool in /var/www/html/app/code/core/Mage/Core/Model/Config.php:534
Stack trace:
#0 /var/www/html/app/code/core/Mage/Core/Model/Config.php(326): Mage_Core_Model_Config->releaseCacheSaveLock()
#1 /var/www/html/app/code/core/Mage/Core/Model/App.php(270): Mage_Core_Model_Config->init(Array)
#2 /var/www/html/app/Mage.php(676): Mage_Core_Model_App->init('default', 'store', Array)
#3 /var/www/html/install.php(114): Mage::app('default')
#4 {main}
  thrown in /var/www/html/app/code/core/Mage/Core/Model/Config.php on line 534
Failed to run openmage-install -s -d -k: exit status 255
```
I never used flags just ```ddev openmage-install``` I didn't encounter any problems. Right now I am trying to find a procedure to get back to the initial stage before running the command with flags.

2024-01-31 22:05 UTC, sreichel commented
Thats not related to the script itself ... you have to clear `var/cache` directory.

Maybe i should add this too.

2024-01-31 22:13 UTC, ADDISON74 commented
I was preparing to write you the same thing. This situation must be foreseen by deleting {cache|session|report|lock} directories from /var/log. If we don't do it we will get that error.

2024-01-31 22:19 UTC, ADDISON74 commented
If {cache | session} directories exist then they must be deleted first. Please add this action to the script.

2024-01-31 22:19 UTC, sreichel commented
Before i fix it ....

1. set maintenance.flag
2. clear cache
3. run install script
4. delete maintenance.flag

???

2024-01-31 22:20 UTC, ADDISON74 commented
It is much better using the maintenance flag.

2024-01-31 22:47 UTC, ADDISON74 commented
I tested the initial DDEV command, not the version modified by this PR.

- I dropped the database
- I created a new one called db
- I deleted /var/log/{cache|session} directories
- I successfully ran the command in Terminal ```ddev openmage-install -s -d -k``` (sample / default / keep)

In the PR description you say that using the command with the flags -d and -s, the table prefix is set incorrectly and the products from the sample package are not displayed. In the database all tables have no prefix. I loaded the Frontend in the browser and all the sample products are displayed. 

At first glance, the initial DDEV command would not have any problem. Am I wrong in the assessment? However, if we look at the script, the proposed change is logical as it should be.

2024-02-01 00:01 UTC, sreichel commented
> I loaded the Frontend in the browser and all the sample products are displayed.

Strange. I can reproduce it with every install try.

Updated PR works flawless for me. Only with dev-mode ON i run into https://github.com/OpenMage/magento-lts/pull/3677.

2024-02-01 15:16 UTC, ADDISON74 requested changes

2024-02-01 15:16 UTC, ADDISON74 commented on .ddev/commands/web/openmage-install
> +  echo "Clear var/cache ..."
Clearing /var/cache directory... 

Just for keeping the same format and and punctuation.

2024-02-01 15:16 UTC, ADDISON74 commented on .ddev/commands/web/openmage-install
> +echo "Enable maintenance mode ..."
Enable maintenance mode ...

Delete the space between mode and ...

2024-02-01 15:16 UTC, ADDISON74 commented on .ddev/commands/web/openmage-install
> +echo "Disable maintenance mode ..."
Remove the blank space between mode and ...

2024-02-01 19:57 UTC, ADDISON74 commented
I deleted everything from the file system and from Docker. I cloned the OpenMage repository, I ran the following commands in order:

```ddev config```
```ddev composer install```
```ddev start```

If I load the Frontend it is fine, there are no categories and products.

Now I run the following command in Terminal:

```php
ubuntu@DESKTOP-GBHMUPN:~/openmage$ ddev openmage-install -s -d -k
OpenMage is already installed. Delete local.xml and drop the database? [y/N] y
Creating Sample Data directory...
Downloading Sample Data...
--2024-02-01 19:48:45--  https://github.com/Vinai/compressed-magento-sample-data/raw/master/compressed-magento-sample-data-1.9.2.4.tgz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/master/compressed-magento-sample-data-1.9.2.4.tgz [following]
--2024-02-01 19:48:45--  https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/master/compressed-magento-sample-data-1.9.2.4.tgz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68614817 (65M) [application/octet-stream]
Saving to: ‘sample_data.tgz’

sample_data.tgz            100%[========================================>]  65.44M   756KB/s    in 82s

2024-02-01 19:50:13 (817 KB/s) - ‘sample_data.tgz’ saved [68614817/68614817]

Uncompressing Sample Data...
Copying Sample Data into the OpenMage directory...
Importing Sample Data into the database...
SUCCESS: 6e6407d09d97a4a4bd1e39497ebfd70a
```

If I load the Frontend, nothing has changed. I have no categories, I have no products. so I was able to reproduce the problem.

I checked out on this PR

```php
ubuntu@DESKTOP-GBHMUPN:~/openmage$ ddev openmage-install -s -d -k
Enable maintenance mode ...
OpenMage is already installed. Delete local.xml and drop the database? [y/N] y
Uncompressing Sample Data...
Copying Sample Data into the OpenMage directory...
Clear var/cache ...
Importing Sample Data into the database...
SUCCESS: 21307e631c8891b6fcae5b9194257cee
Disable maintenance mode ...
```

If I load the Frontend, I have the content on the page from the Magento Sample package. My opinion that PR solves the problem.

2024-02-01 20:02 UTC, ADDISON74 commented
@sreichel - Please make the requested changes in the sentences to approve this PR.

I did not identify this issue before because I always used the command ```ddev openmage-install``` without flags. I am glad it is fine now. DDEV helped me a lot to test OpenMage and I really recommend everyone to do it because it is extremely simple to get a test environment in which everything is quickly configurable, from webser, php version, database and many others.

2024-02-01 22:43 UTC, ADDISON74 approved these changes

2024-02-01 22:55 UTC, sreichel commented
Note: to not get asked for deleting local.xml and drop DB, you can use `-q` ;)

(`-k` to keep downloaded saple data is still optional)

2024-02-02 14:27 UTC, ADDISON74 commented
We need a green approval for this PR. Whoever gives it doesn't have to worry because only two people will use this change.

2024-02-02 15:07 UTC, sreichel commented
> because only two people will use this change

Does really nobody else use ddev?

2024-02-02 19:25 UTC, fballiano commented
is this PR finished? in that case I'll merge it

2024-02-02 20:20 UTC, sreichel commented
Can be merged

2024-02-02 20:33 UTC, merged