Replaced google dashboard charts with Chart.js (via composer)
OpenMage/magento-lts pull request #4435
Opened 2024-12-30 08:10 UTC by sreichel

### Description (*)

- see https://github.com/OpenMage/magento-lts/discussions/3244

https://github.com/chartjs comes with a composer file, but unfortunatly its broken since v3 and has no `dist` directory in it (containing built js and css files). Until its fixed composer plugin tries to download files from https://cdn.jsdelivr.net/npm/chart.js@4.4.7

Multiple datarows may come later.

![dashboard](https://github.com/user-attachments/assets/477c731d-72f1-431d-bf6d-1290eddff558)

### Related Pull Requests

Better JS lazy load from https://github.com/MahoCommerce/maho/commit/b4e66fc0a57f735debf6efc5f88f3956c70190bb

2025-01-01 22:48 UTC, sreichel commented
Draft until composer-pluig v2 is released.

2025-01-09 08:34 UTC, Hanmac commented
You still need to apply the Missing Data fix from this PR #3594

2025-01-09 08:54 UTC, sreichel commented
Of course ...  its just to replace the charts :)

2025-02-05 16:18 UTC, colinmollenhour requested changes
Worked for me after making the one suggested change.

2025-02-05 16:18 UTC, colinmollenhour commented on app/code/core/Mage/Adminhtml/Block/Dashboard.php
> +        $helper = Mage::helper('adminhtml/dashboard');
```suggestion
        $helper = Mage::helper('adminhtml/dashboard_data');
```

2025-02-06 17:35 UTC, colinmollenhour submitted a review, later dismissed

2025-02-06 18:58 UTC, sreichel commented
Fixed conflicts. @addison74 please test it too.

2025-02-06 21:10 UTC, addison74 commented
I checked out this PR and I'm having the following issue. When I visit the Dashboard in the backend it asks me to enable the chart. See the image bellow

![chart_disable](https://github.com/user-attachments/assets/4772e096-21ce-49fa-9b58-c9070cb6d2a1)

If I click on that link it redirects to a page where I have no options related to this chart.

![redirect](https://github.com/user-attachments/assets/81d3b624-f1b8-4ccc-9ccf-4141fa0d5c3c)

2025-02-06 21:40 UTC, sreichel commented
> If I click on that link it redirects to a page where I have no options related to this chart.

Whats inside "Dashboard" group?

2025-02-07 08:53 UTC, addison74 commented
I will check it then update my reply.

2025-02-07 19:48 UTC, addison74 submitted a review, later dismissed

2025-02-07 19:51 UTC, addison74 commented
Just an idea, do we need two more options in the section, "Last 3 Months" and "Last 6 Months"? Could it help better to evaluate the sales?

2025-02-10 21:13 UTC, sreichel commented
Good idea ... coming soon ;)

2025-02-12 22:42 UTC, colinmollenhour approved these changes

2025-02-25 09:09 UTC, sreichel commented
Last PR for next release?

2025-02-25 11:54 UTC, sreichel commented on app/code/core/Mage/Reports/Helper/Data.php
> +    public const PERIOD_6_MONTH     = '6m';
```suggestion
    public const PERIOD_3_MONTHS    = '3m';
    public const PERIOD_6_MONTHS    = '6m';
```

2025-02-28 13:20 UTC, colinmollenhour approved these changes

2025-02-28 16:11 UTC, merged