splitted union queries for eav entities to simpler queries
OpenMage/magento-lts pull request #531
Opened 2018-09-21 07:54 UTC by dng-dev

This is a follow up to the past PR #347.

This pull requests converts EAV - based queries for $model->load() and $collection->load() queries. Affected Entities are catalog_product catalog_categories customers. The idea behind is to convert the SQL - Queries to simpler one which reduces the load on the database and don't create tmp-tables and also depending on the configuration tmp-tables on disc. Instead of having one HUGE query with UNION ALL for the eav tables each table is queried separatly. Another improfement is that the if expression is gone and the order by store_id is happening in PHP which reduces the overall load on the database. Another improfement is the static sorted attribute cache to avoid double sort of attributes when 2 products whinin an listing have the same attribute set.

@seansan @colinmollenhour @tmotyl @partounian the other PR is closed

2018-09-24 16:30 UTC, colinmollenhour commented
Nice work, Daniel, reducing on-disk temp tables would be a great improvement!

I can see for loading collections of products that the result size would be potentially very large, but what about for loading a single product? I'm wondering if in this case the UNION method could be faster due to network latency? If so perhaps the UNION method could be used for single loads and the new one for collection loads?

Would be great to include some examples of the before/after you have experienced from this update. Thanks!

2018-11-15 11:47 UTC, dng-dev commented
Hey @colinmollenhour will try to make some benchmarks.

2020-07-06 16:29 UTC, IvanChepurnyi commented
Maybe it makes sense instead of separating queries use UNION ALL, as UNION ALL does not do any table on disk materialization as it does not need to sort results for merged result.

2020-07-06 17:05 UTC, IvanChepurnyi commented
So this code can be improved in couple of ways:
1. We can remove `store_id` left join in original Magento Catalog EAV collection [here](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Catalog/Model/Resource/Collection/Abstract.php#L103) and replace with `IN(default_store_id, current_store_id)`
2. Then rewrite this method to avoid using `fetchAll` as it basically wastes CPU time on copying data into array that gets disposed just right away [here](https://github.com/OpenMage/magento-lts/blob/6282a9a6b8a4452543b82f52ea785cfff3b6ea79/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php#L1097). It needs to use `query` method on adapter that returns back iterator of PDO statement that can be directly passed into foreach.
3. Override `_setItemAttributeValue` method in `Mage_Catalog_Model_Resource_Collection_Abstract` and check if record has if `store_id` is not zero set value to product, but if `store_id` equal to 0 and value is already present in product - don't do anything. 

In such a way you even get better performance then eliminating UNION ALL as it does reduce latency, the issue in the select query itself.

2020-07-07 18:22 UTC, colinmollenhour commented
Great suggestions! So happy to have contributions from you guys! I think before we can merge any improvements we should have some real-world numbers, though.

P.S. My team uses Ecomdev_PHPUnit daily and are so grateful for it, @IvanChepurnyi!

2020-07-13 10:46 UTC, dng-dev commented
Will work on it in the next time

2020-10-19 19:06 UTC, joshua-bn requested changes

2020-10-19 19:06 UTC, joshua-bn commented on app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php
> +        } else if (false === method_exists($this, 'getDefaultStoreId') || $storeId == 0) {
This can never get to here because line 1140 does a check for `false === method_exists($this, 'getStoreId')`

2020-10-19 19:06 UTC, joshua-bn commented on app/code/core/Mage/Eav/Model/Entity/Abstract.php
> +        } else if (false === method_exists($this, 'getDefaultStoreId') || $storeId == 0) {
It can never get to here because line 1045

2020-10-19 19:15 UTC, joshua-bn commented
> So this code can be improved in couple of ways:
> 
> 1. We can remove `store_id` left join in original Magento Catalog EAV collection [here](https://github.com/OpenMage/magento-lts/blob/1.9.4.x/app/code/core/Mage/Catalog/Model/Resource/Collection/Abstract.php#L103) and replace with `IN(default_store_id, current_store_id)`
> 2. Then rewrite this method to avoid using `fetchAll` as it basically wastes CPU time on copying data into array that gets disposed just right away [here](https://github.com/OpenMage/magento-lts/blob/6282a9a6b8a4452543b82f52ea785cfff3b6ea79/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php#L1097). It needs to use `query` method on adapter that returns back iterator of PDO statement that can be directly passed into foreach.
> 3. Override `_setItemAttributeValue` method in `Mage_Catalog_Model_Resource_Collection_Abstract` and check if record has  `store_id` that is not zero, we set value to product, but if `store_id` equal to 0 and value is already present in product - don't do anything.
> 
> In such a way you even get better performance then eliminating UNION ALL as it does reduce latency, the issue in the select query itself.

Maybe a PR?

2021-12-20 17:46 UTC, joshua-bn commented
> Then rewrite this method to avoid using fetchAll as it basically wastes CPU time on copying data into array that gets disposed just right away here. It needs to use query method on adapter that returns back iterator of PDO statement that can be directly passed into foreach.

That might be a micro-optimization that doesn't really do anything for this. I see a benefit in it collecting the values first. That way you can throw/catch any issues before calling _setItemAttributeValue() (which sets values and may throw its own exceptions)

2022-06-02 10:41 UTC, fballiano commented
This PR is based on 1.9.3.x which is a non-maintained branch at this point. Since we can't work on this anymore I'm closing it. @dng-dev if you feel like rewriting the PR on 1.9.4.x feel absolutely free to reopen it, it will be much appreciated.

2022-06-14 16:13 UTC, fballiano commented
it's sad to see such great ideas posted, commented and abandoned :-(

2023-05-12 17:49 UTC, fballiano commented
This PR has too many unanswered questions, it was a great idea but it totally abandoned since more than 2 years and it needs to be rebased to "main" and has conflicts. sorry guys, I've labeled "don't forget this PR" but I'll close it.

I'd love to see it fixed and reopened but I've zero hope for that.

2023-05-12 17:49 UTC, closed without merging